# Text Pre-Processing

In [1]:
# Import libraries
import pandas as pd

In [2]:
# Load dataset
df = pd.read_csv('IMDB Dataset.csv')
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

##### Lower casing

In [3]:
# lower case
df['review'] = df['review'].str.lower()
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

##### remove html tags

In [4]:
# Remove Html tags
import re
def remove_html_tags(text):
    html_pattern = re.compile('<.*?>')
    return html_pattern.sub(r'', text)
df['review'] = df['review'].apply(lambda text: remove_html_tags(text))
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [5]:
def remove_url(text) :
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

In [6]:
text = 'Check out my notebook https://www.kaggle.com/campusx/notebook8223fc1abb'
text2 = 'Check out my notebook http:/ /www.kaggle.com/campusx/notebook8223fc1abb'
text3 = 'Google search here www.google.com'
text4 = 'For notebook click "https://www.kaggle.com/campusx/notebook8223fclabb" to search check www.google.com'

In [7]:
remove_url(text)

'Check out my notebook '

In [8]:
remove_url(text2)

'Check out my notebook http:/ /'

##### Remove Punctuation

In [9]:
import string
exclude = string.punctuation

In [10]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [11]:
def remove_punc(text):
     return text.translate(str.maketrans('', '', exclude))

In [12]:
text = 'Hi, how are you? Where: You are! :)() Are you OK?// ahh/'

In [13]:
remove_punc(text)

'Hi how are you Where You are  Are you OK ahh'

In [46]:
df2 = pd.read_csv('twitter_data/train.csv')

In [47]:
df2.sample(5)

          id  label                                              tweet
3060    3061      0  #saturday #morning #blessedramadan   very good...
12732  12733      0                       father's day! #googledoodle
9113    9114      0  be   be #beautiful  #mymaceeleighlife #mymllif...
7316    7317      0           can't wait to sta college   #collegelife
20257  20258      0  working on song 3 of my #ep  !   #musicisthera...

In [48]:
df2['tweet'] = df['tweet'].apply(remove_punc)

In [49]:
df2.head(5)

   id  label                                              tweet
0   1      0   user when a father is dysfunctional and is so...
1   2      0  user user thanks for lyft credit i cant use ca...
2   3      0                                bihday your majesty
3   4      0  model   i love u take with u all the time in u...
4   5      0               factsguide society now    motivation

##### Spelling Correction

In [50]:
from textblob import TextBlob

In [33]:
incorrect_text = 'howw arre yoou, whatt ari yyu doiing?'
blob = TextBlob(incorrect_text)
blob.correct().string

'how are you, what are you doing?'

##### Remove Stopwords

In [42]:
from nltk.corpus import stopwords
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [43]:
def remove_stopwords(text):
    new_text = []
    for word in text.split():
        if word not in stopwords.words('english'):
            new_text.append(word)
    return " ".join(new_text)

In [45]:
remove_stopwords("The quick brown fox jumps over the lazy dog.")

'The quick brown fox jumps lazy dog.'

##### Handle Emojis

In [53]:
import re 
def remove_emoji(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [54]:
emoji_text = 'that was amazing, 👍👍👍'
remove_emoji(emoji_text)

'that was amazing, '

In [62]:
import emoji 
def demojize(text):
    return emoji.demojize(text)

In [64]:
demojize('that was amazing, 👍')

'that was amazing, :thumbs_up:'

In [ ]:
demojize('Python is 🔥')

'Python is :fire:'

In [ ]:
demojize('Love this 😘')

'Love this :face_blowing_a_kiss:'

### Tokenization