# Text Pre-Processing

In [2]:
# Import libraries
import pandas as pd

In [3]:
# Load dataset
df = pd.read_csv('IMDB Dataset.csv')
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

##### Lower casing

In [4]:
# lower case
df['review'] = df['review'].str.lower()
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

##### remove html tags

In [5]:
# Remove Html tags
import re
def remove_html_tags(text):
    html_pattern = re.compile('<.*?>')
    return html_pattern.sub(r'', text)
df['review'] = df['review'].apply(lambda text: remove_html_tags(text))
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [6]:
def remove_url(text) :
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

In [7]:
text = 'Check out my notebook https://www.kaggle.com/campusx/notebook8223fc1abb'
text2 = 'Check out my notebook http:/ /www.kaggle.com/campusx/notebook8223fc1abb'
text3 = 'Google search here www.google.com'
text4 = 'For notebook click "https://www.kaggle.com/campusx/notebook8223fclabb" to search check www.google.com'

In [8]:
remove_url(text)

'Check out my notebook '

In [9]:
remove_url(text2)

'Check out my notebook http:/ /'

##### Remove Punctuation

In [10]:
import string
exclude = string.punctuation

In [11]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [12]:
def remove_punc(text):
     return text.translate(str.maketrans('', '', exclude))

In [13]:
text = 'Hi, how are you? Where: You are! :)() Are you OK?// ahh/'

In [14]:
remove_punc(text)

'Hi how are you Where You are  Are you OK ahh'

In [15]:
df2 = pd.read_csv('twitter_data/train.csv')

In [16]:
df2.sample(5)

          id  label                                              tweet
7003    7004      1  @user if i ever met him i would drop that pos ...
8290    8291      1                   @user @user @user haha i get it
23059  23060      0  happy king kamehameha day to everyone/anyody/y...
2539    2540      0   @user happy bihday to my brother man. needed ...
443      444      1  fo woh officer in viral arrest video was âru...

In [17]:
df2['tweet'] = df2['tweet'].apply(remove_punc)

In [18]:
df2.head(5)

   id  label                                              tweet
0   1      0   user when a father is dysfunctional and is so...
1   2      0  user user thanks for lyft credit i cant use ca...
2   3      0                                bihday your majesty
3   4      0  model   i love u take with u all the time in u...
4   5      0               factsguide society now    motivation

##### Spelling Correction

In [19]:
from textblob import TextBlob

In [20]:
incorrect_text = 'howw arre yoou, whatt ari yyu doiing?'
blob = TextBlob(incorrect_text)
blob.correct().string

'how are you, what are you doing?'

##### Remove Stopwords

In [21]:
from nltk.corpus import stopwords
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [22]:
def remove_stopwords(text):
    new_text = []
    for word in text.split():
        if word not in stopwords.words('english'):
            new_text.append(word)
    return " ".join(new_text)

In [23]:
remove_stopwords("The quick brown fox jumps over the lazy dog.")

'The quick brown fox jumps lazy dog.'

##### Handle Emojis

In [24]:
import re 
def remove_emoji(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [25]:
emoji_text = 'that was amazing, 👍👍👍'
remove_emoji(emoji_text)

'that was amazing, '

In [26]:
import emoji 
def demojize(text):
    return emoji.demojize(text)

In [27]:
demojize('that was amazing, 👍')

'that was amazing, :thumbs_up:'

In [28]:
demojize('Python is 🔥')

'Python is :fire:'

In [29]:
demojize('Love this 😘')

'Love this :face_blowing_a_kiss:'

### Tokenization

##### 1.Split function

In [30]:
# word tokenization
sent1 = 'I am going to karachi'
sent1.split()

['I', 'am', 'going', 'to', 'karachi']

In [31]:
# sentence tokenization
sent2 = 'I am going to karachi. I am going to Lahore'
sent2.split('.')

['I am going to karachi', ' I am going to Lahore']

In [32]:
# problems with split function
sent3 = 'I am going to karachi!'
sent3.split()

['I', 'am', 'going', 'to', 'karachi!']

In [33]:
sent4 = "Where do think, we should go? I think we should go to Lahore."
sent4.split('.')

['Where do think, we should go? I think we should go to Lahore', '']

##### 2. Regular Expression

In [34]:
import re
tokens = re.findall("[\w']+", sent4)
tokens

['Where',
 'do',
 'think',
 'we',
 'should',
 'go',
 'I',
 'think',
 'we',
 'should',
 'go',
 'to',
 'Lahore']

In [35]:
text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book. """
sentences = re.compile('[.!?] ').split(text) 
sentences

["Lorem Ipsum is simply dummy text of the printing and typesetting industry?\nLorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book",
 '']

##### 3. NLTK

In [36]:
from nltk.tokenize import word_tokenize, sent_tokenize

In [37]:
print(sent4)
print(sent_tokenize(sent4))
print(word_tokenize(sent4))

Where do think, we should go? I think we should go to Lahore.
['Where do think, we should go?', 'I think we should go to Lahore.']
['Where', 'do', 'think', ',', 'we', 'should', 'go', '?', 'I', 'think', 'we', 'should', 'go', 'to', 'Lahore', '.']

In [38]:
## if word_tokenize and sent_tokenize give error.
# then use . 
# # !python -m textblob.download_corpora

In [39]:
text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book. """

sent_tokenize(text)

['Lorem Ipsum is simply dummy text of the printing and typesetting industry?',
 "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

In [40]:
sent5 = 'I will do Ph.D in A.I'
sent6 = "We're here to help! mail us at xyz@gmail.com"
sent7 = 'A 10km ride cost $6.30'

In [41]:
word_tokenize(sent5)

['I', 'will', 'do', 'Ph.D', 'in', 'A.I']

In [42]:
word_tokenize(sent6)

['We',
 "'re",
 'here',
 'to',
 'help',
 '!',
 'mail',
 'us',
 'at',
 'xyz',
 '@',
 'gmail.com']

In [43]:
word_tokenize(sent7)

['A', '10km', 'ride', 'cost', '$', '6.30']

##### 4. Spacy

In [44]:
# import spacy
# nlp = spacy.load('en_core_web_sm')

In [45]:
# doc1 = nlp(sent5)
# doc2 = nlp(sent6)
# doc3 = nlp(sent7)

# print(doc1)
# print(doc2)
# print(doc3)

In [1]:
# for token in doc1:
#     print(token)

#### Stemming
- `In grammar, inflection is the modification of a word to
express different grammatical categories such as tense,
case, voice, aspect, person, number, gender, and mood.` 

- `Stemming is the process of reducing inflection in words
to their root forms such as mapping a group of words to
the same stem even if the stem itself is not a valid word in
the Lanơuaơe`

In [46]:
from nltk.stem import PorterStemmer

In [53]:
ps = PorterStemmer()
def stem(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [59]:
sam = "Walk walks walking walked learn learns learning learned"
stem(sam)

'walk walk walk walk learn learn learn learn'

In [ ]:
text = '''probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or
more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more 11
ke dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling
if i had a dozen thumbs theyd all be up for this movie'''
stem(text)

'probabl my alltim favorit movi a stori of selfless sacrific and dedic to a nobl caus but it not preachi or bore it just never get old despit my have seen it some 15 or more time in the last 25 year paul luka perform bring tear to my eye and bett davi in one of her veri few truli sympathet role is a delight the kid are as grandma say more 11 ke dressedup midget than children but that onli make them more fun to watch and the mother slow awaken to what happen in the world and under her own roof is believ and startl if i had a dozen thumb theyd all be up for thi movi'