## Bag of Word

In [11]:
import pandas as pd
import numpy as np

In [12]:
df = pd.DataFrame({'text':['people watch campusX', 'campusX watch campusX', 'people write comment','campusX write comment'],
                   'output':[1,0,1,0,]})
df.head()

                    text  output
0   people watch campusX       1
1  campusX watch campusX       0
2   people write comment       1
3  campusX write comment       0

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(1,2))
bow = cv.fit_transform(df['text']).toarray()

In [14]:
print(cv.vocabulary_)

{'people': 4, 'watch': 7, 'campusx': 0, 'people watch': 5, 'watch campusx': 8, 'campusx watch': 1, 'write': 9, 'comment': 3, 'people write': 6, 'write comment': 10, 'campusx write': 2}

In [15]:
cv.transform(['campusX watch and write comment of campusX']).toarray()

array([[2, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1]])

### On real dataset

In [17]:
df = pd.read_csv('cleaned_train.csv', nrows=1000 , usecols=['label', 'tweet'])
df.head()

   label                                              tweet
0      0  user when a father be dysfunctional and be so ...
1      0  user user thanks for lyft credit i cant use ca...
2      0                                bihday your majesty
3      0  model i love u take with u all the time in urð...
4      0                  factsguide society now motivation

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))
X = cv.fit_transform(df['tweet']).toarray()
X.shape

(1000, 9385)

In [19]:
print(cv.vocabulary_)

{'user when father': 8452, 'when father be': 8820, 'father be dysfunctional': 2351, 'be dysfunctional and': 856, 'dysfunctional and be': 2094, 'and be so': 411, 'be so selfish': 998, 'so selfish he': 6612, 'selfish he drag': 6378, 'he drag his': 3302, 'drag his kid': 2061, 'his kid into': 3422, 'kid into his': 4040, 'into his dysfunction': 3806, 'his dysfunction run': 3418, 'user user thanks': 8424, 'user thanks for': 8362, 'thanks for lyft': 7006, 'for lyft credit': 2601, 'lyft credit cant': 4450, 'credit cant use': 1719, 'cant use cause': 1458, 'use cause they': 8093, 'cause they dont': 1485, 'they dont offer': 7443, 'dont offer wheelchair': 2033, 'offer wheelchair van': 5371, 'wheelchair van in': 8816, 'van in pdx': 8495, 'in pdx disapointed': 3692, 'pdx disapointed getthanked': 5699, 'bihday your majesty': 1207, 'model love take': 4691, 'love take with': 4398, 'take with all': 6898, 'with all the': 8950, 'all the time': 273, 'the time in': 7311, 'time in urð': 7586, 'factsguide society now': 2296, 'society now motivation': 6641, '22 huge fan': 54, 'huge fan fare': 3524, 'fan fare and': 2326, 'fare and big': 2343, 'and big talk': 412, 'big talk before': 1176, 'talk before they': 6905, 'before they leave': 1127, 'they leave chaos': 7452, 'leave chaos and': 4151, 'chaos and pay': 1508, 'and pay dispute': 476, 'pay dispute when': 5690, 'dispute when they': 1944, 'when they get': 8834, 'they get there': 7446, 'get there allshowandnogo': 2884, 'user camp tomorrow': 8161, 'camp tomorrow user': 1424, 'tomorrow user user': 7901, 'user user user': 8429, 'user user dannyâ': 8400, 'the next school': 7226, 'next school year': 5057, 'school year be': 6321, 'year be the': 9119, 'be the year': 1022, 'the year for': 7359, 'year for examsð': 9120, 'for examsð cant': 2569, 'examsð cant think': 2255, 'cant think about': 1457, 'think about that': 7473, 'about that school': 131, 'that school exam': 7051, 'school exam hate': 6319, 'exam hate imagine': 2252, 'hate imagine actorslife': 3211, 'imagine actorslife revolutionschool': 3629, 'actorslife revolutionschool girl': 160, 'we won love': 8715, 'won love the': 9021, 'love the land': 4400, 'the land allin': 7185, 'land allin cavs': 4102, 'allin cavs champion': 282, 'cavs champion cleveland': 1487, 'champion cleveland clevelandcavaliers': 1499, 'user user welcome': 8431, 'user welcome here': 8447, 'welcome here im': 8761, 'here im it': 3378, 'im it so': 3605, 'it so gr8': 3890, 'ireland consumer price': 3815, 'consumer price index': 1674, 'price index mom': 5909, 'index mom climbed': 3755, 'mom climbed from': 4697, 'climbed from previous': 1584, 'from previous 02': 2772, 'previous 02 to': 5906, '02 to 05': 1, 'to 05 in': 7603, '05 in may': 2, 'in may blog': 3677, 'may blog silver': 4551, 'blog silver gold': 1259, 'silver gold forex': 6498, 'we be so': 8679, 'so selfish orlando': 6613, 'selfish orlando standwithorlando': 6380, 'orlando standwithorlando pulseshooting': 5556, 'standwithorlando pulseshooting orlandoshooting': 6718, 'pulseshooting orlandoshooting biggerproblems': 5953, 'orlandoshooting biggerproblems selfish': 5558, 'biggerproblems selfish heabreaking': 1180, 'selfish heabreaking value': 6379, 'heabreaking value love': 3321, 'get to see': 2888, 'to see my': 7797, 'see my daddy': 6350, 'my daddy today': 4864, 'daddy today 80days': 1779, 'today 80days gettingfed': 7868, 'user cnn call': 8167, 'cnn call michigan': 1593, 'call michigan middle': 1415, 'michigan middle school': 4643, 'middle school build': 4644, 'school build the': 6318, 'build the wall': 1348, 'the wall chant': 7338, 'wall chant tcot': 8613, 'no comment in': 5095, 'comment in australia': 1630, 'in australia opkillingbay': 3646, 'australia opkillingbay seashepherd': 709, 'opkillingbay seashepherd helpcovedolphins': 5518, 'seashepherd helpcovedolphins thecove': 6335, 'helpcovedolphins thecove helpcovedolphins': 3356, 'ouchjunior be angryð': 5570, 'be angryð got7': 823, 'angryð got7 junior': 544, 'got7 junior yugyoem': 3022, 'junior yugyoem omg': 3973, 'be thankful for': 1006, 'thankful for have': 6994, 'for have paner': 2582, 'have paner thankful': 3263, 'paner thankful positive': 5672, 'retweet if you': 6137, 'if you agree': 3565, 'it friday smile': 3855, 'friday smile all': 2724, 'smile all around': 6553, 'all around via': 235, 'around via ig': 617, 'via ig user': 8515, 'ig user user': 3575, 'user user cooky': 8399, 'user cooky make': 8175, 'cooky make people': 1680, 'we all know': 8674, 'all know essential': 245, 'know essential oil': 4070, 'essential oil be': 2191, 'oil be not': 5384, 'be not make': 949, 'not make of': 5155, 'make of chemical': 4487, 'euro2016 people blame': 2203, 'people blame ha': 5710, 'blame ha for': 1246, 'ha for concede': 3106, 'for concede goal': 2558, 'concede goal wa': 1650, 'goal wa it': 2966, 'wa it fat': 8582, 'it fat rooney': 3851, 'fat rooney who': 2350, 'rooney who give': 6217, 'who give away': 8886, 'give away free': 2919, 'away free kick': 714, 'free kick know': 2706, 'kick know bale': 4036, 'know bale can': 4069, 'bale can hit': 780, 'can hit them': 1438, 'hit them from': 3430, 'them from there': 7380, 'sad little dude': 6246, 'little dude badday': 4281, 'dude badday coneofshame': 2083, 'badday coneofshame cat': 775, 'coneofshame cat piss': 1658, 'cat piss funny': 1481, 'piss funny laugh': 5777, 'product of the': 5926, 'of the day': 5318, 'the day happy': 7143, 'day happy man': 1828, 'happy man wine': 3182, 'man wine tool': 4518, 'wine tool who': 8938, 'tool who it': 7922, 'who it the': 8889, 'it the weekend': 3896, 'the weekend time': 7345, 'weekend time to': 8755, 'time to open': 7592, 'to open up': 7768, 'open up amp': 5511, 'up amp drink': 8056, 'amp drink up': 354, 'user user lumpy': 8409, 'user lumpy say': 8272, 'lumpy say be': 4443, 'say be prove': 6289, 'be prove it': 974, 'prove it lumpy': 5946, 'user tgif ff': 8359, 'tgif ff to': 6966, 'ff to my': 2432, 'to my gamedev': 7760, 'my gamedev indiedev': 4890, 'gamedev indiedev indiegamedev': 2826, 'indiedev indiegamedev squad': 3759, 'indiegamedev squad user': 3760, 'squad user user': 6702, 'beautiful sign by': 1087, 'sign by vendor': 6493, 'by vendor 80': 1404, 'vendor 80 for': 8498, '80 for 4500': 102, 'for 4500 upsideofflorida': 2540, '4500 upsideofflorida shopalyssas': 80, 'upsideofflorida shopalyssas love': 8079, 'user all smile': 8115, 'all smile when': 260, 'smile when medium': 6562, 'when medium be': 8823, 'medium be pressconference': 4611, 'be pressconference in': 972, 'pressconference in antalya': 5896, 'in antalya turkey': 3643, 'antalya turkey sunday': 572, 'turkey sunday throwback': 8007, 'sunday throwback love': 6814, 'we have great': 8694, 'have great panel': 3244, 'great panel on': 3048, 'panel on the': 5671, 'on the mediatization': 5445, 'the mediatization of': 7203, 'mediatization of the': 4610, 'of the public': 5328, 'the public service': 7264, 'public service ica16': 5951, 'happy father day': 3170, 'father day user': 2360, '50 people go': 87, 'people go to': 5715, 'go to nightclub': 2959, 'to nightclub to': 7763, 'nightclub to have': 5089, 'to have good': 7716, 'have good night': 3242, 'good night and': 3002, 'night and man': 5077, 'and man action': 460, 'man action mean': 4508, 'action mean those': 157, 'mean those people': 4605, 'those people be': 7548, 'people be lose': 5709, 'be lose to': 925, 'lose to their': 4346, 'to their family': 7842, 'their family forever': 7366, 'family forever riporlando': 2313, 'have never have': 3254, 'never have chance': 5007, 'have chance to': 3235, 'chance to vote': 1501, 'to vote for': 7855, 'vote for presidential': 8562, 'for presidential candidate': 2627, 'presidential candidate wa': 5894, 'candidate wa excite': 1452, 'wa excite about': 8573, 'excite about and': 2257, 'about and this': 116, 'and this cycle': 516, 'this cycle look': 7499, 'cycle look to': 1759, 'look to be': 4331, 'to be no': 7634, 'be no different': 941, 'alohafriday time doe': 290, 'time doe not': 7580, 'doe not exist': 1993, 'not exist positivevibes': 5144, 'exist positivevibes hawaiian': 2267, 'positivevibes hawaiian user': 5865, 'hawaiian user user': 3294, 'user rip to': 8330, 'rip to the': 6181, 'to the fellow': 7830, 'the fellow nohern': 7160, 'fellow nohern ireland': 2411, 'nohern ireland fan': 5120, 'ireland fan who': 3816, 'fan who sadley': 2332, 'who sadley pass': 8892, 'sadley pass away': 6255, 'pass away tonight': 5680, 'away tonight gawa': 720, 'tonight gawa forever': 7903, 'gawa forever sing': 2835, 'forever sing and': 2680, 'sing and cheer': 6511, 'and cheer on': 414, 'cheer on fire': 1523, 'it wa hard': 3908, 'wa hard monday': 8579, 'hard monday due': 3199, 'monday due to': 4710, 'due to cloudy': 2085, 'to cloudy weather': 7654, 'cloudy weather disable': 1590, 'weather disable oxygen': 8719, 'disable oxygen production': 1933, 'oxygen production for': 5651, 'production for today': 5927, 'for today goodnight': 2659, 'today goodnight badmonday': 7881, 'it unbelievable that': 3902, 'unbelievable that in': 8034, 'that in the': 7033, 'in the 21st': 3705, 'the 21st century': 7077, '21st century wed': 52, 'century wed need': 1495, 'wed need something': 8724, 'need something like': 4984, 'something like this': 6654, 'like this again': 4250, 'this again neverump': 7486, 'again neverump xenophobia': 204, 'taylorswift1989 bull up': 6923, 'bull up you': 1356, 'up you will': 8075, 'you will dominate': 9265, 'will dominate your': 8917, 'dominate your bull': 2012, 'your bull and': 9276, 'bull and you': 1352, 'and you will': 531, 'you will direct': 9264, 'will direct it': 8914, 'direct it whatever': 1929, 'it whatever you': 3910, 'whatever you want': 8815, 'you want it': 9262, 'want it to': 8616, 'it to do': 3897, 'morning travelingram dalat': 4777, 'travelingram dalat ripinkylife': 7962, 'user once more': 8312, 'once more only': 5472, 'more only one': 4752, 'only one word': 5503, 'one word tell': 5492, 'word tell it': 9036, 'tell it all': 6945, 'it all photoshop': 3835, 'all photoshop enoughisenough': 257, 'photoshop enoughisenough dontphotoshopeverything': 5762, 'enoughisenough dontphotoshopeverything wheresallthenaturalphotos': 2174, 'oh cedarpoint wait': 5382, 'cedarpoint wait hour': 1491, 'wait hour in': 8605, 'hour in the': 3478, 'in the valravn': 3724, 'the valravn line': 7328, 'valravn line and': 8493, 'line and it': 4261, 'and it stop': 445, 'it stop work': 3894, 'stop work we': 6762, 'work we be': 9051, 'be so close': 991, 'thankful for sunshine': 7001, 'for sunshine thankful': 2635, 'sunshine thankful positive': 6828, 'when you finally': 8838, 'you finally finish': 9185, 'finally finish book': 2444, 'finish book youve': 2468, 'book youve be': 1286, 'youve be work': 9328, 'be work on': 1058, 'work on for': 9047, 'on for awhile': 5412, 'for awhile bookworm': 2550, 'awhile bookworm ontothenextnovel': 726, 'yup be knicks': 9341, 'be knicks fan': 913, 'knicks fan be': 4067, 'fan be hard': 2324, 'be hard so': 883, 'hard so it': 3200, 'so it easy': 6597, 'it easy to': 3850, 'easy to just': 2104, 'to just be': 7729, 'just be an': 3979, 'be an nba': 820, 'an nba fan': 396, 'nba fan when': 4971, 'fan when the': 2331, 'when the playoff': 8832, 'the playoff roll': 7254, 'playoff roll around': 5813, 'there be life': 7398, 'be life after': 920, 'life after social': 4199, 'after social networking': 192, 'social networking embrace': 6639, 'networking embrace each': 5000, 'embrace each day': 2140, 'each day be': 2096, 'my mom share': 4916, 'mom share the': 4699, 'share the same': 6425, 'the same bihday': 7280, 'same bihday user': 6264, 'bihday user bihday': 1203, 'user bihday snake': 8154, 'bihday snake see': 1196, 'snake see you': 6569, 'see you this': 6366, 'you this weekend': 9250, 'lovely echeveria bloomsflowers': 4420, 'echeveria bloomsflowers grow': 2112, 'bloomsflowers grow gardening': 1263, 'grow gardening iphonesia': 3066, 'gardening iphonesia bliss': 2832, 'iphonesia bliss bloom': 3812, 'bliss bloom basilicabotanica': 1253, 'be amaze iam': 816, 'amaze iam positive': 325, 'iam positive affirmation': 3543, 'whenever im and': 8847, 'im and something': 3592, 'and something go': 502, 'something go wrong': 6653, 'feel blue illustration': 2394, 'the best pa': 7102, 'best pa about': 1161, 'pa about life': 5655, 'about life be': 121, 'life be know': 4202, 'be know who': 914, 'know who you': 4087, 'who you be': 8894, 'you be ¼ð': 9162, 'abc2020 get ready': 110, 'get ready remove': 2875, 'ready remove the': 6061, 'remove the victums': 6115, 'the victums frm': 7333, 'victums frm pulseclub': 8524, 'frm pulseclub prayfororlando': 2752, 'for her bihday': 2585, 'her bihday we': 3361, 'bihday we get': 1204, 'we get her': 8692, 'get her nose': 2860, 'her nose job': 3368, 'nose job user': 5127, 'job user bihday': 3951, 'user bihday petunia': 8151, 'bihday petunia we': 1189, 'petunia we love': 5753, 'we love you': 8700, 'off to concelebrate': 5366, 'to concelebrate at': 7661, 'concelebrate at the': 1651, 'at the albanpilgrimage': 676, 'the albanpilgrimage for': 7083, 'albanpilgrimage for the': 223, 'for the first': 2644, 'the first time': 7164, 'first time user': 2486, 'user let the': 8263, 'let the scumbaggery': 4182, 'the scumbaggery begin': 7286, 'thank you super': 6983, 'you super love': 9247, 'super love it': 6831, 'love it zpamdelacruz': 4373, 'it zpamdelacruz wedding': 3916, 'zpamdelacruz wedding dolores': 9353, 'wedding dolores capas': 8727, 'dolores capas tarlac': 2010, 'scourge on those': 6326, 'on those play': 5453, 'those play baroque': 7549, 'play baroque piece': 5797, 'baroque piece on': 790, 'piece on piano': 5772, 'on piano beyond': 5434, 'piano beyond belief': 5763, 'user let fight': 8262, 'let fight against': 4176, 'fight against love': 2435, 'against love peace': 206, 'happy fatherâ day': 3171, 'fatherâ day mr': 2379, 'day mr rayos': 1839, 'mr rayos video': 4808, 'rayos video father': 6040, 'video father day': 8528, 'father day rayos': 2357, 'day rayos world': 1845, 'rayos world hotvideo': 6041, 'world hotvideo video': 9066, 'user ascot time': 8131, 'ascot time with': 629, 'time with this': 7598, 'with this babe': 8991, 'this babe ascot': 7487, 'babe ascot fashion': 735, 'ascot fashion monochrome': 628, 'fashion monochrome style': 2346, 'monochrome style instahappyday': 4723, 'the weekendis hereð': 7346, 'weekendis hereð selfie': 8758, 'hereð selfie yolo': 3388, 'selfie yolo xoxo': 6376, 'yolo xoxo like4like': 9146, 'happy at work': 3159, 'at work conference': 686, 'work conference right': 9041, 'conference right mindset': 1661, 'right mindset lead': 6162, 'mindset lead to': 4664, 'lead to cultureofdevelopment': 4139, 'to cultureofdevelopment organization': 7665, 'cultureofdevelopment organization work': 1739, 'organization work mindset': 5544, 'christina grimmies last': 1554, 'grimmies last performance': 3061, 'last performance before': 4112, 'performance before be': 5741, 'before be shot': 1122, 'be shot via': 988, 'shot via user': 6462, 'via user christinarip': 8518, 'user christinarip voice': 8166, 'christinarip voice christinagrimmie': 1558, 'we be ready': 8678, 'be ready to': 977, 'ready to dance': 6063, 'to dance roar': 7666, 'dance roar preschooler': 1793, 'roar preschooler student': 6198, 'preschooler student proudâ': 5889, 'youve really hu': 9332, 'really hu my': 6072, 'hu my feel': 3520, 'user my wife': 8290, 'my wife whom': 4943, 'wife whom adore': 8904, 'whom adore have': 8895, 'adore have to': 174, 'have to miss': 3279, 'to miss your': 7753, 'miss your poland': 4684, 'your poland show': 9308, 'poland show because': 5830, 'show because she': 6471, 'because she have': 1098, 'she have surgery': 6430, 'have surgery her': 3270, 'surgery her name': 6846, 'her name be': 3367, 'name be bridget': 4961, 'be bridget amp': 838, 'bridget amp shes': 1325, 'amp shes my': 373, 'shes my everything': 6438, 'user be so': 8142, 'be so jealous': 995, 'so jealous of': 6598, 'jealous of you': 3940, 'of you right': 5357, 'you right now': 9240, 'right now chatiado': 6165, 'celebrate every man': 1492, 'every man that': 2229, 'man that ha': 4517, 'that ha played': 7027, 'ha played it': 3112, 'played it fatherly': 5810, 'it fatherly role': 3852, 'fatherly role father': 2371, 'role father day': 6209, 'im sure they': 3621, 'sure they be': 6843, 'they be just': 7433, 'be just happy': 909, 'just happy ½ð': 3994, 'happy ½ð ½ð': 3194, '½ð ½ð hour': 9367, 'the white establishment': 7348, 'white establishment cant': 8867, 'establishment cant have': 2193, 'cant have blk': 1453, 'have blk folx': 3231, 'blk folx run': 1254, 'folx run around': 2522, 'run around love': 6229, 'around love themselves': 614, 'love themselves and': 4402, 'themselves and promote': 7388, 'and promote our': 484, 'promote our greatness': 5937, 'good morning the': 3001, 'morning the journey': 4776, 'the journey begin': 7182, 'journey begin travel': 3958, 'begin travel yeah': 1133, 'travel yeah thejourneybegins': 7961, 'yeah thejourneybegins helloâ': 9114, 'user if you': 8238, 'if you luv': 3570, 'you luv hottweets': 9216, 'luv hottweets like': 4448, 'hottweets like this': 3476, 'like this from': 4251, 'this from venusexchangeâ': 7503, 'our new brochure': 5588, 'new brochure have': 5019, 'brochure have arrive': 1334, 'have arrive how': 3226, 'arrive how excite': 623, 'how excite aworks': 3499, 'excite aworks solution': 2258, 'so much stuff': 6604, 'much stuff happen': 4814, 'stuff happen in': 6777, 'happen in florida': 3137, 'in florida first': 3659, 'florida first orlando': 2499, 'first orlando shoot': 2483, 'orlando shoot and': 5554, 'shoot and now': 6452, 'and now disneygatorattack': 472, 'now disneygatorattack on': 5195, 'disneygatorattack on two': 1941, 'on two year': 5459, 'two year old': 8025, 'year old kidð': 9122, 'user ferrari will': 8199, 'ferrari will do': 2420, 'will do itð': 8915, 'do itð ªð': 1959, 'itð ªð for': 3922, 'ªð for the': 9354, 'for the sake': 2653, 'the sake of': 7279, 'sake of the': 6259, 'of the championship': 5315, 'the championship this': 7120, 'championship this gp': 1500, 'this gp be': 7508, 'gp be clearly': 3026, 'be clearly turn': 843, 'clearly turn point': 1574, 'turn point rb': 8010, 'point rb ferrarimercsð': 5826, 'ace my first': 153, 'my first test': 4881, 'first test proud': 2485, 'seek probe into': 6367, 'probe into udtapunjab': 5922, 'into udtapunjab leak': 3810, 'udtapunjab leak point': 8028, 'leak point finger': 4146, 'point finger at': 5824, 'finger at amarinder': 2466, 'at amarinder aap': 648, 'user wrap up': 8463, 'wrap up senseaboutmaths': 9091, 'up senseaboutmaths user': 8071, 'senseaboutmaths user 6th': 6391, 'user 6th user': 8108, '6th user user': 97, 'user hey white': 8229, 'hey white people': 3393, 'white people you': 8872, 'people you can': 5736, 'you can call': 9170, 'can call people': 1431, 'call people white': 1418, 'people white by': 5732, 'white by user': 8865, 'by user race': 1403, 'user race identity': 8322, 'race identity medâ': 6000, 'user user you': 8435, 'user you might': 8472, 'you might be': 9220, 'might be just': 4649, 'be just have': 910, 'just have not': 3995, 'have not show': 3260, 'not show here': 5162, 'show here today': 6473, 'here today regurgitate': 3382, 'today regurgitate talk': 7883, 'regurgitate talk point': 6097, 'talk point and': 6907, 'point and name': 5823, 'and name call': 465, 'sometimes you have': 6659, 'you have to': 9203, 'have to raise': 3281, 'to raise few': 7781, 'raise few brow': 6023, 'few brow to': 2424, 'brow to raise': 1340, 'to raise the': 7782, 'raise the bar': 6024, 'the bar golfstrengthandconditioning': 7094, 'bar golfstrengthandconditioning strong': 788, 'golfstrengthandconditioning strong felixfoisgolf': 2976, 'about that greathonour': 130, 'that greathonour careerconvos': 7026, 'greathonour careerconvos user': 3056, 'careerconvos user user': 1470, 'user design innovative': 8181, 'design innovative learn': 1899, 'innovative learn space': 3767, 'learn space user': 4149, 'space user to': 6680, 'user to include': 8378, 'to include wateringhole': 772