## Bag of Word

In [ ]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({'text':['people watch campusX', 'campusX watch campusX', 'people write comment','campusX write comment'],
                   'output':[1,0,1,0,]})
df.head()

                    text  output
0   people watch campusX       1
1  campusX watch campusX       0
2   people write comment       1
3  campusX write comment       0

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
bow = cv.fit_transform(df['text']).toarray()

In [4]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}

In [5]:
cv.transform(['campusX watch and write comment of campusX']).toarray()

array([[2, 1, 0, 1, 1]])

### On real dataset

In [6]:
df = pd.read_csv('cleaned_train.csv', nrows=1000 , usecols=['label', 'tweet'])
df.head()

   label                                              tweet
0      0  user when a father be dysfunctional and be so ...
1      0  user user thanks for lyft credit i cant use ca...
2      0                                bihday your majesty
3      0  model i love u take with u all the time in urð...
4      0                  factsguide society now motivation

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(df['tweet']).toarray()
X.shape

(1000, 3694)

In [8]:
print(cv.vocabulary_)

{'user': 3411, 'when': 3538, 'father': 1184, 'be': 355, 'dysfunctional': 1013, 'and': 208, 'so': 2974, 'selfish': 2853, 'he': 1507, 'drag': 986, 'his': 1552, 'kid': 1810, 'into': 1721, 'dysfunction': 1012, 'run': 2783, 'thanks': 3211, 'for': 1271, 'lyft': 1992, 'credit': 790, 'cant': 583, 'use': 3409, 'cause': 606, 'they': 3242, 'dont': 974, 'offer': 2317, 'wheelchair': 3537, 'van': 3426, 'in': 1656, 'pdx': 2432, 'disapointed': 933, 'getthanked': 1358, 'bihday': 411, 'your': 3644, 'majesty': 2010, 'model': 2132, 'love': 1955, 'take': 3154, 'with': 3571, 'all': 166, 'the': 3215, 'time': 3270, 'urð': 3406, 'factsguide': 1156, 'society': 2979, 'now': 2296, 'motivation': 2161, '22': 39, 'huge': 1599, 'fan': 1169, 'fare': 1176, 'big': 404, 'talk': 3157, 'before': 373, 'leave': 1873, 'chaos': 627, 'pay': 2427, 'dispute': 946, 'get': 1356, 'there': 3233, 'allshowandnogo': 171, 'camp': 573, 'tomorrow': 3289, 'dannyâ': 850, 'next': 2251, 'school': 2826, 'year': 3629, 'examsð': 1125, 'think': 3246, 'about': 105, 'that': 3212, 'exam': 1123, 'hate': 1492, 'imagine': 1649, 'actorslife': 118, 'revolutionschool': 2731, 'girl': 1366, 'we': 3495, 'won': 3580, 'land': 1844, 'allin': 168, 'cavs': 608, 'champion': 620, 'cleveland': 682, 'clevelandcavaliers': 683, 'welcome': 3518, 'here': 1534, 'im': 1646, 'it': 1739, 'gr8': 1411, 'ireland': 1727, 'consumer': 750, 'price': 2557, 'index': 1668, 'mom': 2136, 'climbed': 687, 'from': 1310, 'previous': 2555, '02': 0, 'to': 3278, '05': 1, 'may': 2054, 'blog': 455, 'silver': 2918, 'gold': 1380, 'forex': 1278, 'orlando': 2370, 'standwithorlando': 3031, 'pulseshooting': 2599, 'orlandoshooting': 2371, 'biggerproblems': 407, 'heabreaking': 1510, 'value': 3425, 'see': 2846, 'my': 2194, 'daddy': 834, 'today': 3280, '80days': 90, 'gettingfed': 1359, 'cnn': 695, 'call': 569, 'michigan': 2103, 'middle': 2105, 'build': 543, 'wall': 3475, 'chant': 626, 'tcot': 3178, 'no': 2271, 'comment': 714, 'australia': 292, 'opkillingbay': 2352, 'seashepherd': 2838, 'helpcovedolphins': 1529, 'thecove': 3220, 'ouchjunior': 2378, 'angryð': 212, 'got7': 1404, 'junior': 1789, 'yugyoem': 3656, 'omg': 2337, 'thankful': 3209, 'have': 1500, 'paner': 2413, 'positive': 2520, 'retweet': 2726, 'if': 1628, 'you': 3641, 'agree': 150, 'friday': 1298, 'smile': 2959, 'around': 263, 'via': 3440, 'ig': 1631, 'cooky': 755, 'make': 2012, 'people': 2440, 'know': 1827, 'essential': 1088, 'oil': 2329, 'not': 2289, 'of': 2314, 'chemical': 641, 'euro2016': 1098, 'blame': 447, 'ha': 1458, 'concede': 728, 'goal': 1376, 'wa': 3468, 'fat': 1183, 'rooney': 2771, 'who': 3551, 'give': 1370, 'away': 298, 'free': 1292, 'kick': 1809, 'bale': 330, 'can': 577, 'hit': 1556, 'them': 3224, 'sad': 2796, 'little': 1924, 'dude': 1006, 'badday': 320, 'coneofshame': 735, 'cat': 603, 'piss': 2474, 'funny': 1324, 'laugh': 1855, 'product': 2569, 'day': 861, 'happy': 1481, 'man': 2023, 'wine': 3565, 'tool': 3295, 'weekend': 3512, 'open': 2347, 'up': 3397, 'amp': 200, 'drink': 996, 'lumpy': 1986, 'say': 2822, 'prove': 2587, 'tgif': 3204, 'ff': 1216, 'gamedev': 1339, 'indiedev': 1671, 'indiegamedev': 1672, 'squad': 3019, 'beautiful': 362, 'sign': 2915, 'by': 564, 'vendor': 3432, '80': 89, '4500': 69, 'upsideofflorida': 3402, 'shopalyssas': 2899, 'medium': 2068, 'pressconference': 2547, 'antalya': 231, 'turkey': 3359, 'sunday': 3097, 'throwback': 3259, 'great': 1426, 'panel': 2412, 'on': 2338, 'mediatization': 2067, 'public': 2594, 'service': 2870, 'ica16': 1614, '50': 75, 'go': 1375, 'nightclub': 2262, 'good': 1388, 'night': 2261, 'action': 116, 'mean': 2061, 'those': 3254, 'lose': 1951, 'their': 3221, 'family': 1167, 'forever': 1275, 'riporlando': 2745, 'never': 2236, 'chance': 622, 'vote': 3465, 'presidential': 2545, 'candidate': 582, 'excite': 1127, 'this': 3249, 'cycle': 828, 'look': 1947, 'different': 923, 'alohafriday': 175, 'doe': 954, 'exist': 1132, 'positivevibes': 2522, 'hawaiian': 1504, 'rip': 2741, 'fellow': 1202, 'nohern': 2279, 'sadley': 2799, 'pass': 2419, 'tonight': 3290, 'gawa': 1348, 'sing': 2927, 'cheer': 638, 'fire': 1233, 'hard': 1485, 'monday': 2139, 'due': 1007, 'cloudy': 693, 'weather': 3498, 'disable': 931, 'oxygen': 2398, 'production': 2570, 'goodnight': 1392, 'badmonday': 322, 'unbelievable': 3379, '21st': 37, 'century': 616, 'wed': 3502, 'need': 2225, 'something': 2988, 'like': 1911, 'again': 143, 'neverump': 2237, 'xenophobia': 3616, 'taylorswift1989': 3174, 'bull': 546, 'will': 3558, 'dominate': 968, 'direct': 927, 'whatever': 3534, 'want': 3478, 'do': 953, 'morning': 2155, 'travelingram': 3329, 'dalat': 841, 'ripinkylife': 2744, 'once': 2339, 'more': 2154, 'only': 2344, 'one': 2340, 'word': 3587, 'tell': 3191, 'photoshop': 2463, 'enoughisenough': 1076, 'dontphotoshopeverything': 975, 'wheresallthenaturalphotos': 3543, 'oh': 2328, 'cedarpoint': 612, 'wait': 3471, 'hour': 1588, 'valravn': 3424, 'line': 1916, 'stop': 3056, 'work': 3589, 'close': 689, 'sunshine': 3107, 'finally': 1225, 'finish': 1230, 'book': 483, 'youve': 3651, 'awhile': 301, 'bookworm': 485, 'ontothenextnovel': 2345, 'yup': 3660, 'knicks': 1826, 'easy': 1022, 'just': 1790, 'an': 204, 'nba': 2219, 'playoff': 2489, 'roll': 2765, 'life': 1901, 'after': 139, 'social': 2977, 'networking': 2235, 'embrace': 1056, 'each': 1017, 'share': 2882, 'same': 2807, 'snake': 2966, 'lovely': 1962, 'echeveria': 1029, 'bloomsflowers': 462, 'grow': 1438, 'gardening': 1346, 'iphonesia': 1725, 'bliss': 452, 'bloom': 461, 'basilicabotanica': 343, 'amaze': 188, 'iam': 1612, 'affirmation': 135, 'whenever': 3539, 'wrong': 3607, 'feel': 1199, 'blue': 463, 'illustration': 1641, 'best': 393, 'pa': 2402, '¼ð': 3683, 'abc2020': 103, 'ready': 2664, 'remove': 2703, 'victums': 3444, 'frm': 1309, 'pulseclub': 2598, 'prayfororlando': 2537, 'her': 1533, 'nose': 2287, 'job': 1773, 'petunia': 2454, 'off': 2316, 'concelebrate': 729, 'at': 280, 'albanpilgrimage': 161, 'first': 1237, 'let': 1885, 'scumbaggery': 2835, 'begin': 374, 'thank': 3208, 'super': 3109, 'zpamdelacruz': 3672, 'wedding': 3503, 'dolores': 966, 'capas': 586, 'tarlac': 3166, 'scourge': 2831, 'play': 2486, 'baroque': 339, 'piece': 2470, 'piano': 2464, 'beyond': 398, 'belief': 381, 'fight': 1220, 'against': 144, 'peace': 2433, 'fatherâ': 1187, 'mr': 2172, 'rayos': 2655, 'video': 3445, 'world': 3597, 'hotvideo': 1587, 'ascot': 269, 'babe': 310, 'fashion': 1179, 'monochrome': 2146, 'style': 3079, 'instahappyday': 1698, 'weekendis': 3514, 'hereð': 1536, 'selfie': 2851, 'yolo': 3640, 'xoxo': 3618, 'like4like': 1912, 'conference': 736, 'right': 2739, 'mindset': 2117, 'lead': 1865, 'cultureofdevelopment': 815, 'organization': 2368, 'christina': 663, 'grimmies': 1434, 'last': 1846, 'performance': 2442, 'shot': 2903, 'christinarip': 665, 'voice': 3463, 'christinagrimmie': 664, 'dance': 846, 'roar': 2755, 'preschooler': 2541, 'student': 3073, 'proudâ': 2586, 'really': 2669, 'hu': 1597, 'wife': 3556, 'whom': 3553, 'adore': 125, 'miss': 2123, 'poland': 2504, 'show': 2906, 'because': 363, 'she': 2885, 'surgery': 3121, 'name': 2209, 'bridget': 517, 'shes': 2887, 'everything': 1116, 'jealous': 1760, 'chatiado': 631, 'celebrate': 613, 'every': 1108, 'played': 2487, 'fatherly': 1185, 'role': 2764, 'sure': 3118, '½ð': 3684, 'white': 3547, 'establishment': 1090, 'blk': 453, 'folx': 1261, 'themselves': 3227, 'promote': 2578, 'our': 2379, 'greatness': 1428, 'journey': 1780, 'travel': 3328, 'yeah': 3628, 'thejourneybegins': 3222, 'helloâ': 1527, 'luv': 1990, 'hottweets': 1586, 'venusexchangeâ': 3434, 'new': 2238, 'brochure': 529, 'arrive': 266, 'how': 1593, 'aworks': 304, 'solution': 2984, 'much': 2175, 'stuff': 3076, 'happen': 1476, 'florida': 1251, 'shoot': 2896, 'disneygatorattack': 942, 'two': 3367, 'old': 2333, 'kidð': 1811, 'ferrari': 1211, 'itð': 1744, 'ªð': 3673, 'sake': 2803, 'championship': 621, 'gp': 1409, 'clearly': 681, 'turn': 3360, 'point': 2501, 'rb': 2656, 'ferrarimercsð': 1212, 'ace': 114, 'test': 3201, 'proud': 2584, 'seek': 2847, 'probe': 2565, 'udtapunjab': 3372, 'leak': 1869, 'finger': 1229, 'amarinder': 187, 'aap': 101, 'wrap': 3603, 'senseaboutmaths': 2860, '6th': 83, 'hey': 1538, 'race': 2628, 'identity': 1623, 'medâ': 2069, 'might': 2109, 'regurgitate': 2692, 'sometimes': 2990, 'raise': 2639, 'few': 1215, 'brow': 536, 'bar': 337, 'golfstrengthandconditioning': 1383, 'strong': 3070, 'felixfoisgolf': 1201, 'greathonour': 1427, 'careerconvos': 593, 'design': 905, 'innovative': 1680, 'learn': 1871, 'space': 2999, 'include': 1657, 'wateringhole': 3490, 'cave': 607, 'mountaintop': 2166, 'campfire': 575, 'hâ': 1611, 'altright': 181, 'insecurity': 1684, 'lure': 1989, 'men': 2080, 'whitesupremacy': 3550, 'carry': 600, 'gun': 1450, 'wouldnt': 3601, 'help': 1528, 'control': 752, 'wont': 3582, 'black': 438, 'market': 2035, 'terrorism': 3199, 'bad': 318, 'power': 2532, 'mind': 2114, 'heal': 1512, 'body': 473, 'altwaystoheal': 182, 'healthy': 1514, 'woohoo': 3585, 'over': 2390, 'week': 3511, 'far': 1174, 'place': 2482, 'where': 3541, 'member': 2077, 'hus': 1605, 'rehearse': 2693, 'music': 2186, 'out': 2382, 'announcement': 224, 'midweek': 2108, 'newmusic': 2246, 'watchthisspace': 3487, 'guitar': 1449, '8pm': 92, 'channel': 625, 'what': 3531, 'fuss': 1330, 'watch': 3485, 'episode': 1084, 'offline': 2323, 'very': 3438, 'nice': 2256, 'long': 1944, 'snapchat': 2967, 'redhead': 2682, 'vermillionred': 3436, '15': 19, 'thing': 3245, 'incredibly': 1661, 'yes': 3633, 'receive': 2672, 'acceptance': 111, 'letter': 1889, 'master': 2044, 'back': 316, 'october': 2313, 'goodtimes': 1394, 'history': 1555, 'daughter': 859, 'rid': 2735, 'bike': 420, 'driveway': 1000, 'son': 2992, 'while': 3545, 'enjoy': 1073, 'summeime': 3091, 'memory': 2079, 'station': 3039, 'way': 3494, 'jam': 1751, 'course': 776, 'ill': 1640, 'always': 183, 'hope': 1576, 'hug': 1598, 'but': 556, 'gon': 1387, 'na': 2203, 'anytime': 240, 'soon': 2995, 'couple': 773, 'sex': 2873, 'naked': 2208, 'japanese': 1755, 'hump': 1602, 'humpersð': 1604, 'edwardsville': 1039, 'pennsylvania': 2438, 'personalise': 2449, 'gbp': 1350, '799': 88, 'shop': 2898, 'cool': 756, 'home': 1565, 'fun': 1321, 'some': 2985, 'truly': 3344, 'sick': 2910, 'ppl': 2533, 'trump': 3345, 'obama': 2308, 'resign': 2715, 'boy': 499, 'change': 624, 'nashvilletour2016': 2211, 'nashvilleforever': 2210, 'eurusd': 1103, 'clear': 680, '11400': 11, 'barrier': 340, 'jump': 1786, 'fresh': 1297, '4week': 74, 'high': 1541, 'la': 1836, 'friend': 1302, 'still': 3051, 'head': 1511, 'fact': 1154, 'destroyed': 912, 'dis': 930, 'sta': 3021, 'baking': 326, 'eyelid': 1145, 'vigilfororlando': 3449, 'harp': 1488, 'clonakilty': 688, 'ihavenofriends': 1636, 'someonecomewithme': 2987, 'sundayð': 3101, 'relax': 2695, 'icon': 1617, 'woman': 3578, 'sundaymorning': 3099, 'marilynmonroe': 2033, 'interested': 1716, 'linguistics': 1917, 'doesnt': 955, 'address': 123, 'racism': 2630, 'raciolinguistics': 2629, 'bringsâ': 524, 'beloved': 384, 'cd': 611, 'recover': 2679, 'apple': 247, 'marvel': 2039, 'song': 2993, 'musica': 2187, 'weed': 3509, 'ripchristina': 2742, 'adele': 124, 'vine': 3453, 'why': 3554, 'mocked': 2131, 'brexit': 512, 'under': 3381, 'spell': 3006, 'referendum': 2686, 'commerzbank': 715, '100': 7, 'health': 1513, 'benefit': 386, 'cucumber': 812, 'ofw': 2327, 'pinoy': 2473, 'followme': 1260, 'igers': 1633, 'instagood': 1695, 'toradora': 3300, 'anime': 215, 'animeedit': 218, 'breakup': 509, 'alone': 176, 'lonely': 1942, 'lap': 1845, 'pool': 2514, '10k': 9, 'ride': 2736, 'picked': 2466, 'gym': 1456, 'membership': 2078, 'form': 1281, 'cotd': 766, 'polar': 2505, 'bear': 359, 'climb': 686, 'angry': 211, 'living': 1932, 'cold': 702, 'him': 1548, 'muslim': 2191, 'assassinate': 274, 'snappy': 2968, 'football': 1270, 'fringesqcbagssummer': 1307, 'ó¾': 3693, 'nochebuena': 2273, 'lasvegas': 1847, 'usa': 3407, 'vega': 3429, 'strip': 3068, 'ma': 1998, 'fleurette': 1247, 'instaboyinstamansefieseptumfriend': 1691, 'smilesblackandwhite': 2962, 'branch': 503, 'itâ': 1743, 'rainy': 2638, 'write': 3606, 'tear': 3182, 'fly': 1254, 'bird': 428, 'haiku': 1462, '3lines': 64, 'micropoetry': 2104, 'button': 559, 'mail': 2009, 'me': 2059, 'pretty': 2551, 'jewelrymaking': 1768, 'driver': 999, 'female': 1205, 'moose': 2153, 'river': 2751, 'rd': 2657, 'weston': 3526, 'kill': 1814, 'ok': 2332, 'crew': 793, 'animal': 214, 'afterpas': 141, 'japan': 1754, 'ï¼': 3692, 'madeinjapan': 2001, 'eos': 1083, 'cute': 824, 'cawaii': 609, 'strawberry': 3063, 'tomato': 3288, 'arent': 256, 'protest': 2583, 'republican': 2709, 'wonthey': 3583, 'fuhered': 1319, 'ampâ': 203, 'find': 1227, 'spend': 3007, 'guy': 1454, '146604726015': 18, 'update': 3400, 'analytics': 206, 'photooftheday': 2462, 'anyone': 239, 'date': 858, 'doj': 962, 'fbi': 1196, 'become': 366, 'corrupt': 764, 'emailgate': 1054, 'hillary2016': 1547, 'shameful': 2880, 'disgraceful': 940, 'ridiculous': 2737, 'stupidity': 3077, 'than': 3207, 'even': 1105, 'negligencewhy': 2228, 'put': 2611, 'sachintendulkar': 2795, 'installation': 1700, 'bihdayð': 418, '21thbihday': 38, 'bestfriend': 394, 'loveð': 1970, 'most': 2157, 'impoant': 1652, 'matter': 2051, 'too': 3293, 'sho': 2892, 'pooh4u': 2513, 'chris': 659, 'evansð': 1104, 'actor': 117, 'human': 1600, '³ð': 3674, 'chrisevans': 660, 'bihdayâ': 416, 'heas': 1519, 'thought': 3255, 'prayer': 2536, 'murder': 2185, 'gay': 1349, 'demo': 895, 'album': 163, 'newalbum': 2239, 'indie': 1670, 'echobelly': 1031, 'retweeted': 2727, 'lion': 1918, 'pro': 2563, 'webmareting': 3500, 'seo': 2864, 'community': 717, 'management': 2025, 'nzdusd': 2306, 'target': 3165, 'sma': 2955, '07190': 4, 'ive': 1745, 'ever': 1107, 'bihdayweeksucks': 414, 'bithday27': 434, 'tâ': 3369, 'bless': 449, 'sa': 2793, 'ladiesð': 1840, 'happiest': 1479, 'eah': 1018, 'disneysmagickingdom': 944, 'disney': 941, 'magickingdom': 2006, 'disneyland': 943, 'orlandoâ': 2373, 'kinda': 1817, 'among': 197, 'found': 1285, 'id': 1620, 'exclaim': 1129, 'blain': 446, 'hair': 1463, 'other': 2375, 'nite': 2269, 'lt3': 1977, 'listen': 1922, '17': 22, 'freedom': 1293, 'effo': 1041, 'present': 2542, 'merely': 2086, 'store': 3059, 'past': 2422, 'theodore': 3229, 'rooseveltâ': 2772, 'yall': 3624, 'aint': 157, 'commitment': 716, 'trust': 3347, 'faithful': 1160, 'michelleobama': 2102, 'gorilla': 1403, 'racist': 2631, 'betâ': 397, 'newarkfestival': 2240, '3rd': 65, 'internet': 1719, 'broken': 532, 'netflix': 2232, 'mochithepug': 2130, 'puglife': 2596, 'thatthen': 3214, 'whatbusiness': 3533, 'usual': 3415, 'hbd': 1505, 'dick': 920, 'suckin': 3087, 'tequila': 3196, 'lovin': 1971, 'slut': 2954, 'any': 237, 'justalillate': 1791, 'butstillontime': 558, 'small': 2956, 'hand': 1472, 'barry': 341, 'probably': 2564, 'lie': 1900, 'game': 1338, 'suck': 3086, 'golfâ': 1384, 'everyone': 1113, 'goodmorning': 1390, 'challenge': 618, 'aaps': 102, 'claim': 674, '70': 84, 'punjabi': 2604, 'drugaddicts': 1002, 'dare': 852, 'tracerequest': 3312, 'send': 2859, 'deepest': 885, 'condolence': 734, 'zimbabwe': 3667, 'hea': 1508, 'touch': 3308, 'mato': 2050, 'chapones': 628, 'saturday': 2818, 'afternoon': 140, 'chi': 644, 'meet': 2070, 'soed': 2981, 'nut': 2303, 'bolt': 477, 'bloke': 458, 'aww': 305, 'bing': 424, 'bong': 479, 'dawn': 860, 'month': 2148, 'live': 1927, 'vfest': 3439, 'summer': 3092, '35th': 62, 'shane': 2881, 'robe': 2757, 'watson': 3492, 'cricker': 794, 'million': 2113, 'jewishsupremacist': 1769, 'hear': 1517, 'announcer': 225, 'move': 2167, 'player': 2488, 'or': 2362, 'whoknows': 3552, 'radio1': 2634, 'coldplay': 703, 'god': 1379, 'come': 711, 'through': 3258, 'keep': 1802, 'terrorist': 3200, 'constitutional': 748, 'another': 229, 'excuse': 1130, 'appease': 246, 'nra': 2299, 'measure': 2064, 'gloucesterrugby': 1374, 'together': 3285, 'down': 982, 'fine': 1228, 'dandy': 847, 'exuberant': 1141, 'depressed': 901, 'halffull': 1468, 'halfempty': 1467, 'mikeashley': 2110, 'sposdirectshame': 3015, 'perhapse': 2444, 'example': 1124, 'protect': 2582, 'workersrights': 3591, 'within': 3572, 'europe': 1101, 'euref': 1095, 'remain': 2698, 'stella': 3045, 'princess': 2559, 'birdsstellabadprincess': 430, 'post': 2526, 'wedâ': 3508, 'check': 635, 'saw': 2821, 'shi': 2888, 'care': 591, 'hilarious': 1544, 'already': 177, 'block': 454, 'ask': 273, 'paicularly': 2406, 'difficult': 924, 'question': 2618, 'devastate': 913, 'news': 2247, 'victim': 3443, 'happiness': 1480, 'state': 3037, 'manner': 2028, 'margaret': 2032, 'lee': 1875, 'runbeck': 2784, 'quote': 2623, 'inspirational': 1689, 'safe': 2800, 'acne': 115, 'create': 788, 'beat': 360, 'makingbeats': 2016, 'thursday': 3262, 'istandard': 1736, 'akaiproâ': 159, 'number': 2302, '10': 6, '¾ð': 3687, 'weddingpay': 3505, 'weddingdressâ': 3504, 'forward': 1282, 'attend': 286, 'cipd': 670, 'workshop': 3595, 'cpd': 781, 'onemoreday': 2341, 'reach': 2659, '200': 29, 'follower': 1259, 'twitch': 3365, 'hypu': 1610, 'stream': 3064, 'em': 1053, 'cost': 765, 'verbal': 3435, 'abuse': 110, 'adult': 127, 'teen': 3187, 'country': 772, 'bring': 520, 'bomb': 478, 'stadium': 3022, 'eat': 1023, 'bae': 323, 'swalscha': 3129, 'dejeuner': 891, 'lunch': 1987, 'amoureuxâ': 199, 'ilovethesecret': 1645, 'lawofattraction': 1861, 'quiz': 2622, 'success': 3083, 'joy': 1781, 'lifeâ': 1909, 'libtard': 1898, 'sjw': 2939, 'liberal': 1896, 'politics': 2511, 'pole': 2507, 'bgp': 400, 'rozthediva': 2778, 'blackgirlspole': 441, 'bodyandpole': 474, 'argentina2015': 257, 'attack': 284, '3d': 63, 'empty': 1063, 'city': 672, 'side': 2913, 'selfserving': 2856, 'hypocrite': 1609, 'eye': 1142, 'bounce': 496, 'ball': 331, 'nimrod': 2267, 'president': 2544, 'nohcarolina': 2278, 'whe': 3536, 'building': 544, 'loo': 1946, 'reelection': 2684, 'money': 2143, 'ksleg': 1832, 'could': 768, 'easily': 1020, 'anywhere': 241, 'alreemgroup': 178, 'alyalshahawy': 186, 'ad': 120, 'photographerdubai': 2460, 'sun': 3096, 'mydubaiâ': 2198, 'seem': 2849, 'montreal': 2150, 'wash': 3481, 'spirit': 3008, 'enteainment': 1077, 'brisbane': 525, 'wimbledon2016': 3561, 'entrepreneur': 1079, 'speaker': 3002, 'confident': 737, 'fashionâ': 1181, 'gala': 1336, 'moment': 2137, 'bipolar': 427, 'frikiegirl2016': 1306, 'lucky': 1981, 'chinatown': 651, 'mall': 2022, 'binondoâ': 426, 'isnt': 1733, 'complete': 723, 'utter': 3417, 'moron': 2156, 'trash': 3326, 'america': 194, 'votâ': 3466, 'dad': 833, 'magnettherapy': 2007, 'sebbo': 2841, 'egã': 1043, 'smileâ': 2963, 'smileegsmile': 2960, 'torio': 3303, 'brilliant': 519, 'kettering': 1805, 'customer': 823, 'screen': 2833, 'potp': 2529, 'shock': 2893, 'treatment': 3331, 'toraya': 3301, 'bus': 551, 'alamindah': 160, 'carrieunderwood': 599, 'beer': 372, 'bridpo': 518, 'food': 1264, 'fest': 1213, 'campsite': 576, 'drunk': 1003, 'starstruck': 3035, 'repost': 2707, 'propey': 2580, 'ocean': 2311, 'sydneyâ': 3140, 'teach': 3179, 'felt': 1204, 'pakistan': 2410, 'allin216': 169, 'left': 1877, 'countdown': 770, 'nolefam': 2281, 'milan': 2111, '22092016': 40, 'stone': 3055, 'rise': 2748, 'club': 694, 'reason': 2671, 'stay': 3040, 'nobody': 2272, 'else': 1052, 'hopelly': 1577, 'crush': 804, 'wakow': 3472, 'buzz': 563, 'hookup': 1575, 'app': 245, 'engage': 1069, '298': 47, 'lef': 1876, 'b4': 308, 'end': 1064, 'classez': 676, 'yay': 3625, 'risay18': 2746, 'risaypls': 2747, 'saidâ': 2802, 'legendary': 1880, 'united': 3387, 'rest': 2719, 'proven': 2588, 'own': 2397, 'firearm': 1234, 'hold': 1561, 'door': 976, 'thats': 3213, 'try': 3351, 'deny': 897, 'jeffreycwilliams': 1764, 'buttrue': 560, 'baby': 313, 'knownð': 1829, 'babygirl': 314, 'niece': 2258, 'xo': 3617, 'tbc': 3175, 'oneteamlincoln': 2342, 'carowinds': 598, 'rockthepark': 2762, 'timetogetmyjesuson': 3271, 'bought': 495, 'dory': 978, 'ticket': 3265, 'minute': 2120, 'sixty': 2938, 'second': 2842, 'should': 2905, 'sanjapan': 2812, 'animeconvention': 217, 'september': 2866, 'motoâ': 2163, 'sâ': 3143, 'tech': 3183, 'motos': 2162, 'count': 769, 'mondaymotivation': 2141, 'livelifetothefullest': 1928, 'everydaycounts': 1111, '8degree': 91, 'anna': 219, 'classmate': 677, '92â': 94, 'would': 3599, 'able': 104, 'suppo': 3114, 'event': 1106, 'brentwood'